
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          #请求的时间在这个配置的时间之后，请求会被路由到http://httpbin.org:80/get
          predicates:
          - After=2019-01-20T17:42:47.789-07:00[America/Denver]
