
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          #请求的host为**.wtf.com，请求会被路由到配置的 uri
          predicates:
            - Host=**.wtf.com
