
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          #请求的Header中有X-Request-Id的header名，且header值为数字时，请求会被路由到配置的 uri
          predicates:
            - Header=X-Request-Id, \d+
